### ISSUE TITLE
Theme

### ISSUE THREAD

**Issue by 9mm** [codebryo/dotfiles#1]
Hey, I believe I saw your lessons on vueschool if I'm not mistaking you for someone else.

Do you know what exact theme you have here? I looked at your dotfiles and it doesnt appear to be synthwave?

Thanks!

![image](https://user-images.githubusercontent.com/1386207/93047846-41159880-f612-11ea-89e1-ad8f4f2fe464.png)

**Comment by codebryo** [comment]
@9mm hi - sorry for this really late reply. I just recently moved things back to GitHub so I wasn't really monitoring things here.

Sadly I don't remember and have switched since. It could be I was using [NightOwl](https://marketplace.visualstudio.com/items?itemName=sdras.night-owl) and synthwave without the CSS would be my other guess! 

I really do appreciate the interest. I'll keep better track of these things going forward!

Cheers!
